spring.application.name=backend

#Configuracion de Conexion a Oracle DB
spring.datasource.url=jdbc:oracle:thin:@51.91.10.76:1521/FREEPDB1
spring.datasource.username=app
spring.datasource.password=App123!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACION DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Mejoras
# Tiempo maximo que esperara la app para conseguir una conexion antes de dar error (30 segundos)
spring.datasource.hikari.connection-timeout=30000
# Numero maximo de conexiones simultaneas que se mantendran abiertas con Oracle
spring.datasource.hikari.maximum-pool-size=10
# Tiempo maximo que una conexion puede estar ociosa en el pool antes de cerrarse (10 minutos)
spring.datasource.hikari.idle-timeout=600000

